<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Tenowg.MongoObjects.MongoDistributedLock</PackageId>
	  <Description>Apply Distributed locking to MongoObject, a fluent codegenerated MongoDB ODM</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MongoObject.Core\MongoObject.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<InternalsVisibleTo Include="MongoObject.Tests" />
	</ItemGroup>
</Project>
