using Microsoft.CodeAnalysis;
using MongoObject.SourceGenerator.Helpers;
using MongoObject.SourceGenerator.Interfaces;
using MongoObject.SourceGenerator.Models;
using System.Reflection.Metadata;
using System.Security.Cryptography.X509Certificates;

namespace MongoObject.SourceGenerator.Modules
{
    internal class EncrytionModule : ICodeModule
    {
        public void Execute(SourceProductionContext context, (CommonModel model, Compilation comp) provider)
        {
            var model = provider.model;

            if (!model.IsEncryptedModel) return;

            var sb = new IndentedStringBuilder();

            sb.AppendLine("// Autogenerated");
            sb.AppendLine($"namespace {model.Namespace}");
            using (sb.Block())
            {
                sb.AppendLine($"public class {model.Name}EncryptionBuilder(global::MongoObject.PropertyEncryption.Interfaces.IEncryptedClient client, [global::Microsoft.Extensions.DependencyInjection.FromKeyedServices(\"KmsProviders\")] global::MongoObject.PropertyEncryption.Data.KmsProvidersDictionary providers, global::MongoObject.PropertyEncryption.Data.MongoEncryptionOptions encOptions) : global::MongoObject.Core.Interfaces.IEncryptionBuilder");
                using (sb.Block())
                {
                    sb.AppendLine($"public async Task BuildCollection()");
                    using (sb.Block())
                    {
                        sb.AppendLine("var encryptedFields = new global::MongoDB.Bson.BsonDocument");
                        using (sb.Block(closer: ";"))
                        {
                            using (sb.Block())
                            {
                                sb.AppendLine("\"fields\", new global::MongoDB.Bson.BsonArray");
                                using (sb.Block())
                                {
                                    
                                    foreach (var prop in model.EncryptedModels.Properties)
                                    {
                                        sb.AppendLine("new global::MongoDB.Bson.BsonDocument");
                                        using (sb.Block(closer: ","))
                                        {
                                            sb.AppendLine("{ \"keyId\", global::MongoDB.Bson.BsonNull.Value },");
                                            sb.AppendLine($"{{ \"path\", \"Document.{prop.QueryName}\" }},");
                                            sb.AppendLine($"{{ \"bsonType\", \"{GetBsonTypeString(prop.FullName)}\" }},");
                                            sb.AppendLine("{ \"queries\", new global::MongoDB.Bson.BsonDocument(\"queryType\", \"equality\") }");
                                        }
                                    }
                                }
                            }
                        }
                        sb.AppendLine("var clientEncryptionOptions = new global::MongoDB.Driver.Encryption.ClientEncryptionOptions(");
                        sb.AppendLine("    keyVaultClient: client,");
                        sb.AppendLine($"    keyVaultNamespace: new global::MongoDB.Driver.CollectionNamespace(encOptions.KeyVaultDatabaseName, encOptions.KeyVaultCollectionName),");
                        sb.AppendLine("    kmsProviders: providers");
                        sb.AppendLine(");");
                        sb.AppendLine();
                        sb.AppendLine("var clientEncryption = new global::MongoDB.Driver.Encryption.ClientEncryption(clientEncryptionOptions);");

                        sb.AppendLine($"var createCollectionOptions = new global::MongoDB.Driver.CreateCollectionOptions<global::MongoObject.Core.Data.MongoDocument<global::{model.Namespace}.{model.Name}>>");
                        using (sb.Block(closer: ";"))
                        {
                            sb.AppendLine("EncryptedFields = encryptedFields");
                        }
                        sb.AppendLine("try");
                        using (sb.Block())
                        {
                            sb.AppendLine($"clientEncryption.CreateEncryptedCollection(client.GetDatabase(\"{model.DatabaseName}\"),");
                            sb.AppendLine($"    \"{model.CollectionName}\",");
                            sb.AppendLine("    createCollectionOptions,");
                            sb.AppendLine("    \"local\",");
                            sb.AppendLine("    new global::MongoDB.Bson.BsonDocument());");
                        }
                        sb.AppendLine("catch (Exception ex)");
                        using (sb.Block())
                        {
                            sb.AppendLine("var t = ex;");
                        }
                    }
                }
            }

            context.AddSource($"{model.Namespace.Replace(".", "_")}_{model.Name}.Encryption.g.cs", sb.ToString());
        }

        public static string GetBsonTypeString(string csharpTypeName)
        {
            return csharpTypeName switch
            {
                "string" or "String" or "System.String" => "string",
                "int" or "Int32" or "System.Int32" => "int",
                "long" or "Int64" or "System.Int64" => "long",
                "double" or "Double" or "System.Double" => "double",
                "bool" or "Boolean" or "System.Boolean" => "bool",
                "System.DateTime" or "DateTime" => "date",
                "System.Guid" or "Guid" => "binData",
                "MongoDB.Bson.ObjectId" or "ObjectId" => "objectId",
                "decimal" or "Decimal" or "System.Decimal" => "decimal",
                _ => "object" // Fallback or throw an exception if unsupported by CSFLE
            };
        }
    }
}
