using Microsoft.CodeAnalysis;
using MongoObject.SourceGenerator.Helpers;
using MongoObject.SourceGenerator.Interfaces;
using MongoObject.SourceGenerator.Models;
using System.Collections.Immutable;
using System.Linq;

namespace MongoObject.SourceGenerator.Modules
{
    internal class MongoIndexModule : ICodeModuleMultiple
    {

        public void Execute(SourceProductionContext context, (ImmutableArray<CommonModel?> models, string rootNamespace) args)
        {
            var sb = new IndentedStringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using MongoDB.Driver;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine($"namespace {args.rootNamespace};");
            sb.AppendLine();
            sb.AppendLine($"public class {args.rootNamespace.Replace(".", "")}IndexBuilder : global::MongoObject.Core.Interfaces.IIndexBuilder");
            using (sb.Block())
            {
                sb.AppendLine("public async Task EnsureIndexExists(IServiceProvider sp, bool isAtlasServer)");
                using (sb.Block())
                {
                    foreach (var model in args.models)
                    {
                        if (model == null) continue;
                        sb.AppendLine($"var {model.Name}connection = sp.GetRequiredService<global::MongoObject.Core.Interfaces.IMongoConnection<global::{model.Namespace}.{model.Name}>>();");
                        if (model.Indexes.Count > 0)
                        {
                            sb.AppendLine();
                            sb.AppendLine($"var index{model.Name}Models = new List<global::MongoDB.Driver.CreateIndexModel<global::MongoObject.Core.Data.MongoDocument<global::{model.Namespace}.{model.Name}>>>();");
                            sb.AppendLine();
                            bool? unique = false;
                            string indexName = "";
                            foreach (var index in model.Indexes)
                            {
                                indexName = index.Name;
                                sb.AppendLine($"index{model.Name}Models.Add(new(global::MongoDB.Driver.Builders<global::MongoObject.Core.Data.MongoDocument<global::{model.Namespace}.{model.Name}>>.IndexKeys");
                                foreach (var prop in index.Properties)
                                {
                                    foreach (var ind in prop.Indexes)
                                    {
                                        if (ind.IndexName == index.Name)
                                        {

                                            sb.AppendLine($"    .{ind.Order}(x => x.Document.{prop.Name})");
                                            unique = ind.Unique;
                                        }
                                    }
                                }
                                sb.AppendLine($",new global::MongoDB.Driver.CreateIndexOptions {{ Name = \"{indexName}\", Unique = {unique?.ToString().ToLowerInvariant()} }}));");
                                sb.AppendLine();
                            }
                            sb.AppendLine($"await {model.Name}connection.Collection.Indexes.CreateManyAsync(index{model.Name}Models);");
                            sb.AppendLine();
                        }
                        // build vector index updater
                        sb.AppendLine($"var {model.Name}indexes = await {model.Name}connection.Collection.SearchIndexes.List().ToListAsync();");
                        // for now we are only working with vector indexes
                        sb.AppendLine($"var {model.Name}vectorIndexes = {model.Name}indexes.Where(i => i.Contains(\"type\") && i[\"type\"].AsString == \"vectorSearch\");");
                        // we need to check projections to see if there are any vectors to initialize, as thisn't called from MongoIndex attribute
                        var vectorProjections = model.Projections.Where(x => x.Properties.Any(c => c.EnumName == "Vector" || c.EnumName == "AutoVector"));
                        foreach (var projection in vectorProjections)
                        {

                            sb.AppendLine($"if(!{model.Name}vectorIndexes.Any(x => x.Contains(\"name\") && x[\"name\"].AsString == \"{projection.Name}\"))");
                            using (sb.Block())
                            {
                                if (projection.Properties.Any(x => x.EnumName == "AutoVector"))
                                {
                                    var vectorPropName = projection.Properties.Where(x => x.EnumName == "AutoVector").FirstOrDefault();
                                    // create the vector search
                                    sb.AppendLine($"var {projection.Name}model = new global::MongoDB.Driver.CreateAutoEmbeddingVectorSearchIndexModel<global::MongoObject.Core.Data.MongoDocument<global::{model.Namespace}.{model.Name}>> (");
                                    sb.AppendLine($"    x => x.Document.{vectorPropName.QueryName},");
                                    sb.AppendLine($"    \"{projection.Name}\",");
                                    sb.AppendLine($"    \"{vectorPropName.VectorModel}\"");
                                    // m => m.Runtime, m => m.Year  // Optional filter fields
                                    sb.AppendLine($"    )");
                                    sb.AppendLine($"    {{");
                                    sb.AppendLine($"        Similarity = VectorSimilarity.{vectorPropName.SimilarityType}");
                                    sb.AppendLine($"    }};");
                                    sb.AppendLine($"await {model.Name}connection.Collection.SearchIndexes.CreateOneAsync({projection.Name}model);");
                                }
                                else if (projection.Properties.Any(x => x.EnumName == "Vector"))
                                {
                                    var vectorPropName = projection.Properties.Where(x => x.EnumName == "Vector").FirstOrDefault();
                                    // create the vector search
                                    sb.AppendLine($"var model = new global::MongoDB.Driver.CreateVectorSearchIndexModel<global::MongoObject.Core.Data.MongoDocument<global::{model.Namespace}.{model.Name}>> (");
                                    sb.AppendLine($"    x => x.Document.{projection.Name}Embedding,");
                                    sb.AppendLine($"    \"{projection.Name}\",");
                                    //sb.AppendLine($"                    \"{vectorPropName.VectorModel}\"");
                                    sb.AppendLine($"    VectorSimilarity.{vectorPropName.SimilarityType},");
                                    sb.AppendLine($"    {vectorPropName.VectorDimensions}");
                                    // m => m.Runtime, m => m.Year  // Optional filter fields
                                    sb.AppendLine($"    );");
                                    sb.AppendLine($"await {model.Name}connection.Collection.SearchIndexes.CreateOneAsync(model);");
                                }
                            }
                        }
                    }
                }
            }
            context.AddSource($"{args.rootNamespace.Replace(".", "_")}_IndexBuilder.g.cs", sb.ToString());
        }
    }
}
