services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb-object
    # Standard MongoDB port
    ports:
      - "27018:27017"
    # The --replSet flag is required to enable replica set mode
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: >
        mongosh --port 27017 --quiet --eval "
        try {
          rs.status()
        } catch (e) {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongodb:27017' }]
          })
        }"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_object_data:/data/db
volumes:
  mongo_object_data: