using Microsoft.CodeAnalysis;
using MongoObject.SourceGenerator.Encryption.Helpers;
using MongoObject.SourceGenerator.Encryption.Interfaces;
using MongoObject.SourceGenerator.Encryption.Models;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection.Metadata.Ecma335;

namespace MongoObject.SourceGenerator.Encryption.Modules
{
    internal class ModuleInitializationModule : ICodeModuleMultiple
    {
        public void Execute(SourceProductionContext context, (ImmutableArray<(CommonModel?, EncryptedPropertyModel?)> models, string rootNamespace) args)
        {
            var models = args.models.Where(x => x.Item1 != null).Select(x => x.Item1);
            var encryptedModels = args.models.Where(x => x.Item2 != null).Select(x => x.Item2);
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// Autogenerated");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace MongoObject.Encryption.Generated;");
            sb.AppendLine();
            sb.AppendLine("internal static class EncryptionModuleInitializer");
            using (sb.Block())
            {
                // The runtime guarantees this runs exactly once when the assembly is loaded
                sb.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
                sb.AppendLine("public static void Initialize()");
                using (sb.Block())
                {
                    foreach (var model in models)
                    {
                        // Hook into the core registry you created in Option 2
                        sb.AppendLine("global::MongoObject.Core.Extensions.MongoObjectsPluginRegistry.RegisterDocumentsHook.Add(services =>");
                        using (sb.Block(closer: ");"))
                        {
                            sb.AppendLine($"//{model!.FullQualifiedName}");
                            sb.AppendLine("services.AddKeyedSingleton<MongoObject.PropertyEncryption.Data.KmsProvidersDictionary>(\"KmsProviders\", (sp, _) =>");
                            using (sb.Block(closer: ");"))
                            {
                                sb.AppendLine("var config = sp.GetService<global::Microsoft.Extensions.Configuration.IConfiguration>();");
                                sb.AppendLine("var kmsProviderCredentials = new global::MongoObject.PropertyEncryption.Data.KmsProvidersDictionary();");
                                
                                foreach (var prop in model.Properties)
                                {
                                    if (prop.Local is not null)
                                    {   
                                        sb.AppendLine("try");
                                        using (sb.Block())
                                        {
                                            sb.AppendLine($"var {prop.Name}CustomerMasterKeyBytes = File.ReadAllBytes(\"{prop.Local.BinFilePath}\");");
                                            sb.AppendLine($"if ({prop.Name}CustomerMasterKeyBytes.Length != 96)");
                                            using (sb.Block())
                                            {
                                                sb.AppendLine("throw new Exception(\"Expected the customer master key file to be 96 bytes.\");");
                                            }
                                            sb.AppendLine($"var {prop.Name}LocalOptions = new Dictionary<string, object>");
                                            using (sb.Block(closer: ";"))
                                            {
                                                sb.AppendLine($"{{ \"key\", {prop.Name}CustomerMasterKeyBytes }}");
                                            }
                                            sb.AppendLine($"kmsProviderCredentials.Add(\"{prop.Local.Key}\", {prop.Name}LocalOptions);");
                                        }
                                        sb.AppendLine("catch");
                                        using (sb.Block())
                                        {
                                            sb.AppendLine("throw;");
                                        }
                                    }
                                    else if (prop.Aws is not null)
                                    {
                                        sb.AppendLine($"var {prop.Name}AwsOptions = new Dictionary<string, object>();");
                                        if (prop.Aws.IsOverrided)
                                        {
                                            if (prop.Aws.SessionTokenPath != null)
                                            {
                                                sb.AppendLine($"var {prop.Name}SessionPath = config[\"{prop.Aws.SessionTokenPath}\"];");
                                            }
                                            else if (prop.Aws.AccessKeyPath != null && prop.Aws.SecretKeyPath != null)
                                            {
                                                sb.AppendLine($"{prop.Name}AwsOptions.Add(\"accessKeyId\", config[\"{prop.Aws.AccessKeyPath}\"]);");
                                                sb.AppendLine($"{prop.Name}AwsOptions.Add(\"secretAccessKey\", config[\"{prop.Aws.SecretKeyPath}\"]);");
                                            }
                                        }
                                        sb.AppendLine($"kmsProviderCredentials.Add(\"{prop.Aws.Key}\", {prop.Name}AwsOptions);");
                                    }
                                    else if (prop.Azure is not null)
                                    {
                                        sb.AppendLine($"var {prop.Name}AzureOptions = new Dictionary<string, object>();");
                                        if (prop.Azure.ClientSecretPath != null && prop.Azure.TenantIdPath != null && prop.Azure.ClientIdPath != null)
                                        {
                                            sb.AppendLine($"{prop.Name}AzureOptions.Add(\"tenantId\", config[\"{prop.Azure.TenantIdPath}\"]);");
                                            sb.AppendLine($"{prop.Name}AzureOptions.Add(\"clientId\", config[\"{prop.Azure.ClientIdPath}\"]);");
                                            sb.AppendLine($"{prop.Name}AzureOptions.Add(\"clientSecret\", config[\"{prop.Azure.ClientSecretPath}\"]);");    
                                        }
                                        sb.AppendLine($"kmsProviderCredentials.Add(\"{prop.Azure.Key}\", {prop.Name}AzureOptions);");
                                    }
                                }

                                sb.AppendLine("return kmsProviderCredentials;");
                            }

                            // also add replacements here
                            foreach (var encrypted in encryptedModels)
                            {
                                if (encrypted == null) continue;
                                sb.AppendLine($"// {encrypted.FullQualifiedName}");
                                sb.AppendLine($"services.AddSingleton<global::MongoObject.Core.Interfaces.IMongoConnection<{encrypted.FullQualifiedName}>, global::MongoObject.PropertyEncryption.Services.EncryptedMongoConnection<{encrypted.FullQualifiedName}>>();");
                            }
                        }
                    }
                }
            }

            context.AddSource($"{args.rootNamespace.Replace(".", "_")}_EncryptionInitializer.g.cs", sb.ToString());
        }
    }
}
