using Microsoft.CodeAnalysis;
using MongoObject.SourceGenerator.Encryption.Helpers;
using MongoObject.SourceGenerator.Encryption.Interfaces;
using MongoObject.SourceGenerator.Encryption.Models;
using System.Collections.Immutable;
using System.Linq;

namespace MongoObject.SourceGenerator.Encryption.Modules
{
    internal class ModuleInitializationModule : ICodeModuleMultiple
    {
        public void Execute(SourceProductionContext context, (ImmutableArray<(CommonModel?, EncryptedPropertyModel?)> models, string rootNamespace) args)
        {
            var models = args.models.Where(x => x.Item1 != null).Select(x => x.Item1);
            var encryptedModels = args.models.Where(x => x.Item2 != null).Select(x => x.Item2);
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// Autogenerated");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace MongoObject.Encryption.Generated;");
            sb.AppendLine();
            sb.AppendLine("internal static class EncryptionModuleInitializer");
            using (sb.Block())
            {
                // The runtime guarantees this runs exactly once when the assembly is loaded
                sb.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
                sb.AppendLine("public static void Initialize()");
                using (sb.Block())
                {
                    foreach (var model in models)
                    {
                        // Hook into the core registry you created in Option 2
                        sb.AppendLine("global::MongoObject.Core.Extensions.MongoObjectsPluginRegistry.RegisterDocumentsHook.Add(services =>");
                        using (sb.Block(closer: ");"))
                        {
                            sb.AppendLine($"//{model!.FullQualifiedName}");
                            sb.AppendLine("services.AddKeyedSingleton<MongoObject.PropertyEncryption.Data.KmsProvidersDictionary>(\"KmsProviders\", (sp, _) =>");
                            using (sb.Block(closer: ");"))
                            {
                                sb.AppendLine("var kmsProviderCredentials = new global::MongoObject.PropertyEncryption.Data.KmsProvidersDictionary();");
                                sb.AppendLine("try");
                                using (sb.Block())
                                {
                                    sb.AppendLine("var localCustomerMasterKeyBytes = File.ReadAllBytes(\"crypt-master.key.bin\");");
                                    sb.AppendLine("if (localCustomerMasterKeyBytes.Length != 96)");
                                    using (sb.Block())
                                    {
                                        sb.AppendLine("throw new Exception(\"Expected the customer master key file to be 96 bytes.\");");
                                    }
                                    sb.AppendLine("var localOptions = new Dictionary<string, object>");
                                    using (sb.Block(closer: ";"))
                                    {
                                        sb.AppendLine("{ \"key\", localCustomerMasterKeyBytes }");
                                    }
                                    sb.AppendLine("kmsProviderCredentials.Add(\"local\", localOptions);");
                                }
                                sb.AppendLine("catch");
                                using (sb.Block())
                                {
                                    sb.AppendLine("throw;");
                                }

                                sb.AppendLine("return kmsProviderCredentials;");
                            }

                            // also add replacements here
                            foreach (var encrypted in encryptedModels)
                            {
                                sb.AppendLine($"// {encrypted.FullQualifiedName}");
                                sb.AppendLine($"services.AddSingleton<global::MongoObject.Core.Interfaces.IMongoConnection<{encrypted.FullQualifiedName}>, global::MongoObject.PropertyEncryption.Services.EncryptedMongoConnection<{encrypted.FullQualifiedName}>>();");
                            }
                        }
                    }
                }
            }

            context.AddSource($"{args.rootNamespace.Replace(".", "_")}_EncryptionInitializer.g.cs", sb.ToString());
        }
    }
}
