<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <PackageId>Tenowg.MongoObjects.CliTool</PackageId>
	  <Description>A Cli tool for Tenowg.MongoObjects</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>mo</ToolCommandName>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
	  <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MongoObject.Core\MongoObject.Core.csproj" />
  </ItemGroup>

</Project>
