using System;
using System.Collections.Generic;
using System.Text;

namespace MongoObject.Core.Data
{
    public class MongoObjectOptions
    {
        /// <summary>
        /// The MongoDB connection string used to create your client,
        /// this is optional, and only needed for use with the cli client.
        /// </summary>
        public string? ConnectionString { get; set; }
        public string DatabaseName { get; set; } = string.Empty;

        /// <summary>
        /// The duration for which document data is considered fresh in the cache.
        /// After this time, the cache will attempt to refresh from the database.
        /// Defaults to 10 minutes.
        /// </summary>
        public TimeSpan CacheSoftDuration { get; set; } = TimeSpan.FromMinutes(10);

        /// <summary>
        /// The maximum duration for which configuration data is cached.
        /// After this time, the cache entry is evicted regardless of freshness.
        /// Defaults to 24 hours.
        /// </summary>
        public TimeSpan CacheHardDuration { get; set; } = TimeSpan.FromHours(24);

        /// <summary>
        /// The prefix used for cache keys to avoid collisions.
        /// Defaults to "mongo_cfg_".
        /// </summary>
        public string CachePrefix { get; set; } = "mongo_cfg_";

        public string MongoSystemDatabaseName { get; set; } = "mongo_system";
        /// <summary>
        /// The collection under SystemDatabase that stores the Distributed locka
        /// NOTE: This will be moving to MongoDistributedLock config.
        /// </summary>
        public string DistributedLockCollectionName { get; set; } = "__DistributedLock";
        /// <summary>
        /// The collection name used under SystemDatabase to store migration details
        /// Defaults to "__Migrations"
        /// </summary>
        public string MigrationCollectionName { get; set; } = "__Migrations";
        /// <summary>
        /// The folder used under your project that will hold any migration Class generated by the cli
        /// Defaults to "Migrations"
        /// </summary>
        public string MigrationFolder { get; set; } = "Migrations";
        public TimeSpan DistributedLockDefaultLockDuration { get; set; } = TimeSpan.FromMinutes(10);
        public TimeSpan WatchPollInterval { get; set; } = TimeSpan.FromSeconds(15);
        /// <summary>
        /// Is the database connection an Atlas Server, this will enable some features not available in the Community Additions
        /// </summary>
        public bool IsAtlasMongoDBInstance { get; set; }
    }
}
