using System.Security.Cryptography.X509Certificates;
using System.Text.Json;
using CliTool;
using MongoObject.CliTool.Data;
using Spectre.Console;

namespace MongoObject.CliTool.Helpers
{
    internal class FileBuilder(string projectDirectory, DocumentConfiguration document, OperationDictionary operations, BuildSettings settings, string projectNamespace)
    {
        private IndentedStringBuilder _sb = new();
        private IndentedStringBuilder _opSb = new();

        public void BuildHeaders()
        {
            _sb.AppendLine("// Autogenerated, this will be overwritten the next time migrations are built.");
            _sb.AppendLine("using MongoDB.Driver;");
            _sb.AppendLine("using MongoDB.Bson;");
            _sb.AppendLine("using MongoDB.Driver.Encryption;");
            _sb.AppendLine();
            _sb.AppendLine($"namespace {projectNamespace}.Migration");
            using (_sb.Block())
            {
                _sb.AppendLine("public partial class MigrationBuilder : IMigration");
                using(_sb.Block())
                {
                    _sb.AppendLine("private Dictionary<string, IReadOnlyDictionary<string, object>>? kmsProviders;");
                    _sb.AppendLine("private IMongoClient _client;");
                    _sb.AppendLine("private IMongoClient? _encryptionClient = null;");
                    _sb.AppendLine($"private string Environment = \"{settings.Environment}\";");
                    _sb.AppendLine();
                    _sb.AppendLine("public MigrationBuilder()");
                    using(_sb.Block())
                    {
                        _sb.AppendLine("var kmsData = MongoObject.Core.Extensions.MongoObjectsPluginRegistry.SchemaDocument.GetValue(\"kmsProviders\", null);");
                        _sb.AppendLine("kmsProviders = kmsData != null ? MongoDB.Bson.Serialization.BsonSerializer.Deserialize<Dictionary<string, IReadOnlyDictionary<string, object>>>(");
                        _sb.AppendLine("    kmsData.AsBsonDocument");
                        _sb.AppendLine(") : null;");

                        _sb.AppendLine("var connection_string = MongoObject.Core.Extensions.MongoObjectsPluginRegistry.SchemaDocument[\"connection_string\"].AsString;");
                        _sb.AppendLine("var clientSettings = MongoClientSettings.FromUrl(new MongoUrl(connection_string));");
                        _sb.AppendLine("_client = new MongoClient(clientSettings);");
                        _sb.AppendLine("if (kmsProviders != null)");
                        using (_sb.Block())
                        {
                            _sb.AppendLine("MongoClientSettings.Extensions.AddAutoEncryption();");
                            _sb.AppendLine("var extraOptions = new Dictionary<string, object>");
                            using (_sb.Block(closer: "};"))
                            {
                                _sb.AppendLine($"{{ \"cryptSharedLibPath\", @\"{document.MongoCryptPath}\" }} // Path to your Automatic Encryption Shared Library");
                            };

                            _sb.AppendLine("var autoEncryptionOptions = new AutoEncryptionOptions(");
                            _sb.AppendLine($"    new CollectionNamespace(\"{document.KeyVaultDatabaseName}\", \"{document.KeyVaultCollectionName}\"),");
                            _sb.AppendLine("    kmsProviders,");
                            _sb.AppendLine("    extraOptions: extraOptions);");

                            _sb.AppendLine("    var autoClientSettings = MongoClientSettings.FromUrl(new MongoUrl(connection_string));");
                            _sb.AppendLine("    autoClientSettings.AutoEncryptionOptions = autoEncryptionOptions;");

                            _sb.AppendLine("    _encryptionClient = new MongoClient(autoClientSettings);");
                        }
                    }
                }
            }
            BuildOperations();
            SaveFile();
        }

        private void BuildOperations()
        {
            _opSb.AppendLine("// Autogenerated, this will be overwritten the next time migrations are built.");
            _opSb.AppendLine("using MongoDB.Driver;");
            _opSb.AppendLine("using MongoDB.Bson;");
            _opSb.AppendLine("using MongoDB.Driver.Encryption;");
            _opSb.AppendLine();
            _opSb.AppendLine($"namespace {projectNamespace}.Migration");
            using (_opSb.Block())
            {
                var options = new JsonSerializerOptions { WriteIndented = true };
                var operationString = JsonSerializer.Serialize(operations, options);
                //var escapedOperationString = JsonSerializer.Serialize(operationString);
                _opSb.AppendLine("public partial class MigrationBuilder");
                using (_opSb.Block())
                {
                _opSb.AppendLine("public static string Operations = \"\"\"");
                _opSb.AppendLine(operationString);
                _opSb.Append("\"\"\";");
                _opSb.AppendLine();
                }
            }
        }

        public int SaveFile()
        {
            var migrationDirectory = Path.Combine(projectDirectory, "Migrations");
            if (!AnsiConsole.Confirm($"Confirm migration Directory ({migrationDirectory})?"))
            {
                // we will ask them to fix there project setup and try again.
                AnsiConsole.MarkupLine("[green]Installing...[/]");
            }
            AnsiConsole.WriteLine($"Storing migration file in {migrationDirectory}");
            if (!AnsiConsole.Confirm("Contining will erase any previous migrations and write the new one, proceed?"))
            {
                // we will exit gracefully and inform them to try again later.
                AnsiConsole.MarkupLine("[green]Installing...[/]");
            }

            if (Directory.Exists(migrationDirectory))
            {
                DirectoryInfo di = new DirectoryInfo(migrationDirectory);
                foreach (FileInfo file in di.GetFiles()) file.Delete();
                foreach (DirectoryInfo dir in di.GetDirectories()) dir.Delete(true);
            }
            else
            {
                Directory.CreateDirectory(migrationDirectory);
            }
            Console.WriteLine("Fild created");
            var migrationFilePath = Path.Combine(migrationDirectory, "Migration.Entry.cs");
            File.WriteAllText(migrationFilePath, _sb.ToString());
            var operationsFilePath = Path.Combine(migrationDirectory, "Migration.Operations.cs");
            File.WriteAllText(operationsFilePath, _opSb.ToString());
            return 0;
        }
    }
}