<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Tenowg.MongoObjects.PropertyEncryption</PackageId>
	  <Description>Apply Encryption to MongoObject, a fluent codegenerated MongoDB ODM</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <!-- <Target Name="EnsureCorrectMongoEncryption" AfterTargets="Build;Publish" Condition="$([MSBuild]::IsOsPlatform('Linux'))">
  Revisit this if it becomes an issue
    <ItemGroup>
      <_MongoLib Include="$(PkgMongoDB_Driver_Encryption)\runtimes\linux-x64\native\libmongocrypt.so" />
    </ItemGroup>
    <Copy SourceFiles="@(_MongoLib)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target> -->

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver.Encryption" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MongoObject.Core\MongoObject.Core.csproj" />
  </ItemGroup>
	
  <ItemGroup>
	<None Include="..\MongoObject.SourceGenerator.Encryption\bin\$(Configuration)\netstandard2.0\MongoObject.SourceGenerator.Encryption.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
  
  <ItemGroup>
	<ProjectReference Include="..\MongoObject.SourceGenerator.Encryption\MongoObject.SourceGenerator.Encryption.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
