# Paths matching your dual-output docfx.json setup
$llmFolder = "./_site/llm-api"
$indexFile = "$llmFolder/api-index.md"

if (-not (Test-Path $llmFolder)) {
    Write-Error "LLM API directory not found. Please run 'docfx metadata' first."
    exit 1
}

Write-Host "Generating LLM-friendly API Index..." -ForegroundColor Cyan

# 1. Initialize the index file with a system prompt context for your agent
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# API Reference Map for AI Agents")
[void]$sb.AppendLine("This map contains a flat directory of available APIs. Read this file first to find the exact markdown path for any class, interface, method, or namespace before parsing deeper.")
[void]$sb.AppendLine()

# 2. Grab all Markdown files generated by DocFX (ignoring toc files)
$mdFiles = Get-ChildItem -Path $llmFolder -Filter "*.md" -Recurse | Where-Object { $_.Name -notmatch "toc" -and $_.Name -notmatch "api-index" }

foreach ($file in $mdFiles) {
    # Read the first few lines to find the actual symbol name (usually header # or Title metadata)
    $content = Get-Content $file.FullName -Head 5
    $titleLine = $content | Where-Object { $_ -match "^#\s+(.+)" }
    
    if ($titleLine -and $titleLine -match "^#\s+(.+)") {
        $symbolName = $Matches[1].Trim()
        # Relative path from the root of the llm folder
        $relativePath = $file.FullName.Replace((Get-Item $llmFolder).FullName, ".").Replace("\", "/")
        
        # Determine symbol type for easier agent filtering
        $type = "Class/Member"
        if ($symbolName -match "Namespace") { $type = "Namespace" }
        elseif ($file.Name -match "interface") { $type = "Interface" }
        
        [void]$sb.AppendLine("- **$symbolName** ($type) -> Read details in: $relativePath")
    }
}

# 3. Save out the file
$sb.ToString() | Out-File -FilePath $indexFile -Encoding utf8
Write-Host "Index successfully built at: $indexFile" -ForegroundColor Green
